import 'package:flutter/material.dart';
import '../../presentation/theme/app_colors.dart';

/// Health tier representing general financial vitality
enum HealthTier {
  excellent, // 85 - 100 (Prima)
  good,      // 70 - 84 (Stabil)
  caution,   // 50 - 69 (Waspada)
  deficit,   // < 50 (Kritis)
}

/// Single financial health pillar metric breakdown
class HealthPillarMetric {
  final String title;
  final String description;
  final double score; // 0..100
  final String displayValue;
  final String benchmark;
  final bool isHealthy;

  const HealthPillarMetric({
    required this.title,
    required this.description,
    required this.score,
    required this.displayValue,
    required this.benchmark,
    required this.isHealthy,
  });
}

/// Complete diagnostic report generated by FinancialHealthService
class FinancialHealthReport {
  final int overallScore; // 0..100
  final HealthTier tier;
  final HealthPillarMetric emergencyRunway;
  final HealthPillarMetric fixedCommitment;
  final HealthPillarMetric savingsMargin;
  final HealthPillarMetric spendPacing;
  final List<String> recommendations;
  final double totalLiquidAssets;
  final double totalPocketsAmount;

  const FinancialHealthReport({
    required this.overallScore,
    required this.tier,
    required this.emergencyRunway,
    required this.fixedCommitment,
    required this.savingsMargin,
    required this.spendPacing,
    required this.recommendations,
    required this.totalLiquidAssets,
    required this.totalPocketsAmount,
  });

  Color get tierColor {
    switch (tier) {
      case HealthTier.excellent:
        return AppColors.neoMint;
      case HealthTier.good:
        return AppColors.neoChartreuse;
      case HealthTier.caution:
        return const Color(0xFFFFA439);
      case HealthTier.deficit:
        return AppColors.statusDeficit;
    }
  }

  String get tierLabel {
    switch (tier) {
      case HealthTier.excellent:
        return 'Prima';
      case HealthTier.good:
        return 'Stabil';
      case HealthTier.caution:
        return 'Waspada';
      case HealthTier.deficit:
        return 'Kritis';
    }
  }

  String get tierHeadline {
    switch (tier) {
      case HealthTier.excellent:
        return 'Keuanganmu Berada di Kondisi Prima!';
      case HealthTier.good:
        return 'Keuangan Stabil, Siap Ditingkatkan.';
      case HealthTier.caution:
        return 'Perlu Penyesuaian Pengeluaran.';
      case HealthTier.deficit:
        return 'Arus Kas Memerlukan Evaluasi Segera.';
    }
  }
}
