import 'package:flutter/material.dart';
import '../../data/database/app_database.dart';
import '../../presentation/theme/app_colors.dart';
import 'cashflow_analytics_service.dart';
import 'safe_to_spend_service.dart';

/// Health tier representing general financial vitality
enum HealthTier {
  excellent, // 85 - 100 (Prima)
  good,      // 70 - 84 (Stabil)
  caution,   // 50 - 69 (Waspada)
  deficit,   // < 50 (Kritis)
}

/// Single financial health pillar metric breakdown
class HealthPillarMetric {
  final String title;
  final String description;
  final double score; // 0..100
  final String displayValue;
  final String benchmark;
  final bool isHealthy;

  const HealthPillarMetric({
    required this.title,
    required this.description,
    required this.score,
    required this.displayValue,
    required this.benchmark,
    required this.isHealthy,
  });
}

/// Complete diagnostic report generated by FinancialHealthService
class FinancialHealthReport {
  final int overallScore; // 0..100
  final HealthTier tier;
  final HealthPillarMetric emergencyRunway;
  final HealthPillarMetric fixedCommitment;
  final HealthPillarMetric savingsMargin;
  final HealthPillarMetric spendPacing;
  final List<String> recommendations;
  final double totalLiquidAssets;
  final double totalPocketsAmount;

  const FinancialHealthReport({
    required this.overallScore,
    required this.tier,
    required this.emergencyRunway,
    required this.fixedCommitment,
    required this.savingsMargin,
    required this.spendPacing,
    required this.recommendations,
    required this.totalLiquidAssets,
    required this.totalPocketsAmount,
  });

  Color get tierColor {
    switch (tier) {
      case HealthTier.excellent:
        return AppColors.neoMint;
      case HealthTier.good:
        return AppColors.neoChartreuse;
      case HealthTier.caution:
        return const Color(0xFFFFA439);
      case HealthTier.deficit:
        return AppColors.statusDeficit;
    }
  }

  String get tierLabel {
    switch (tier) {
      case HealthTier.excellent:
        return 'Prima';
      case HealthTier.good:
        return 'Stabil';
      case HealthTier.caution:
        return 'Waspada';
      case HealthTier.deficit:
        return 'Kritis';
    }
  }

  String get tierHeadline {
    switch (tier) {
      case HealthTier.excellent:
        return 'Keuanganmu Berada di Kondisi Prima!';
      case HealthTier.good:
        return 'Keuangan Stabil, Siap Ditingkatkan.';
      case HealthTier.caution:
        return 'Perlu Penyesuaian Pengeluaran.';
      case HealthTier.deficit:
        return 'Arus Kas Memerlukan Evaluasi Segera.';
    }
  }
}

/// Pure Dart domain engine for comprehensive personal finance health diagnostics.
class FinancialHealthService {
  /// Evaluates financial health based on liquid assets, pockets, recurring bills,
  /// cashflow trends, and safe-to-spend pacing.
  static FinancialHealthReport evaluate({
    required List<WalletEntry> wallets,
    required List<PocketEntry> pockets,
    required List<SubscriptionEntry> subscriptions,
    required MonthlyCashflow monthlyCashflow,
    required SafeToSpendMetrics safeToSpend,
    DateTime? referenceDate,
  }) {
    // 1. Total liquid assets & pockets
    double totalLiquidAssets = 0.0;
    for (final w in wallets) {
      totalLiquidAssets += w.balance;
    }

    double totalPocketsAmount = 0.0;
    double emergencyAndRetirementPockets = 0.0;
    for (final p in pockets) {
      totalPocketsAmount += p.currentAmount;
      if (p.type == 'emergency' || p.type == 'retirement' || p.type == 'savings') {
        emergencyAndRetirementPockets += p.currentAmount;
      }
    }

    // Benchmark monthly expense: use actual monthly expense if present,
    // otherwise fallback to subscription commitments or baseline
    double monthlyExpenseBenchmark = monthlyCashflow.expense;
    if (monthlyExpenseBenchmark <= 0) {
      double subSum = 0.0;
      for (final s in subscriptions) {
        subSum += s.cost;
      }
      monthlyExpenseBenchmark = subSum > 0 ? subSum : 1000000.0;
    }

    // Benchmark monthly income
    double monthlyIncomeBenchmark = monthlyCashflow.income;
    if (monthlyIncomeBenchmark <= 0) {
      monthlyIncomeBenchmark = monthlyExpenseBenchmark > 0 ? monthlyExpenseBenchmark : 1000000.0;
    }

    // =========================================================================
    // PILAR 1: EMERGENCY RUNWAY (Ketahanan Dana Darurat) - 30%
    // =========================================================================
    final double totalEmergencyBuffer = totalLiquidAssets + emergencyAndRetirementPockets;
    final double runwayMonths = monthlyExpenseBenchmark > 0
        ? (totalEmergencyBuffer / monthlyExpenseBenchmark)
        : 0.0;

    double emergencyScore;
    if (runwayMonths >= 6.0) {
      emergencyScore = 100.0;
    } else if (runwayMonths >= 3.0) {
      emergencyScore = 70.0 + ((runwayMonths - 3.0) / 3.0) * 30.0;
    } else if (runwayMonths >= 1.0) {
      emergencyScore = 40.0 + ((runwayMonths - 1.0) / 2.0) * 30.0;
    } else {
      emergencyScore = (runwayMonths.clamp(0.0, 1.0)) * 40.0;
    }

    final emergencyPillar = HealthPillarMetric(
      title: 'Dana Darurat (Runway)',
      description: 'Kemampuan bertahan jika tanpa pemasukan',
      score: emergencyScore.clamp(0.0, 100.0),
      displayValue: '${runwayMonths.toStringAsFixed(1)} Bulan',
      benchmark: 'Ideal: ≥ 3–6 Bulan',
      isHealthy: runwayMonths >= 3.0,
    );

    // =========================================================================
    // PILAR 2: FIXED COMMITMENT RATIO (Beban Tagihan Rutin) - 25%
    // =========================================================================
    double totalRecurringBills = 0.0;
    for (final s in subscriptions) {
      totalRecurringBills += s.cost;
    }

    final double commitmentRatio = monthlyIncomeBenchmark > 0
        ? (totalRecurringBills / monthlyIncomeBenchmark) * 100.0
        : 0.0;

    double commitmentScore;
    if (commitmentRatio <= 20.0) {
      commitmentScore = 100.0;
    } else if (commitmentRatio <= 35.0) {
      commitmentScore = 80.0 + ((35.0 - commitmentRatio) / 15.0) * 20.0;
    } else if (commitmentRatio <= 50.0) {
      commitmentScore = 50.0 + ((50.0 - commitmentRatio) / 15.0) * 30.0;
    } else {
      commitmentScore = (100.0 - commitmentRatio).clamp(10.0, 50.0);
    }

    final commitmentPillar = HealthPillarMetric(
      title: 'Beban Tagihan Tetap',
      description: 'Porsi langganan & cicilan dari pemasukan',
      score: commitmentScore.clamp(0.0, 100.0),
      displayValue: '${commitmentRatio.toStringAsFixed(0)}%',
      benchmark: 'Ideal: ≤ 30%',
      isHealthy: commitmentRatio <= 35.0,
    );

    // =========================================================================
    // PILAR 3: NET SAVINGS MARGIN (Tingkat Tabungan) - 25%
    // =========================================================================
    final double netSavings = monthlyCashflow.income - monthlyCashflow.expense;
    final double savingsMarginPercent = monthlyIncomeBenchmark > 0
        ? (netSavings / monthlyIncomeBenchmark) * 100.0
        : 0.0;

    double savingsScore;
    if (savingsMarginPercent >= 20.0) {
      savingsScore = 100.0;
    } else if (savingsMarginPercent >= 10.0) {
      savingsScore = 70.0 + ((savingsMarginPercent - 10.0) / 10.0) * 30.0;
    } else if (savingsMarginPercent >= 0.0) {
      savingsScore = 40.0 + (savingsMarginPercent / 10.0) * 30.0;
    } else {
      savingsScore = (40.0 + savingsMarginPercent).clamp(0.0, 40.0);
    }

    final savingsPillar = HealthPillarMetric(
      title: 'Margin Tabungan Bersih',
      description: 'Sisa arus kas yang berhasil disimpan',
      score: savingsScore.clamp(0.0, 100.0),
      displayValue: '${savingsMarginPercent.toStringAsFixed(0)}%',
      benchmark: 'Ideal: ≥ 15–20%',
      isHealthy: savingsMarginPercent >= 10.0,
    );

    // =========================================================================
    // PILAR 4: SPEND PACING / SAFE-TO-SPEND BUFFER - 20%
    // =========================================================================
    double pacingScore;
    switch (safeToSpend.healthStatus) {
      case FinancialHealthStatus.comfortable:
        pacingScore = 100.0;
        break;
      case FinancialHealthStatus.caution:
        pacingScore = 65.0;
        break;
      case FinancialHealthStatus.deficit:
        pacingScore = 25.0;
        break;
    }

    final pacingPillar = HealthPillarMetric(
      title: 'Disiplin Belanja Harian',
      description: 'Kepatuhan pengeluaran terhadap batas aman',
      score: pacingScore,
      displayValue: safeToSpend.statusLabel,
      benchmark: 'Target: Sangat Aman',
      isHealthy: safeToSpend.healthStatus == FinancialHealthStatus.comfortable,
    );

    // =========================================================================
    // WEIGHTED OVERALL SCORE
    // =========================================================================
    final double weightedScore = (0.30 * emergencyPillar.score) +
        (0.25 * commitmentPillar.score) +
        (0.25 * savingsPillar.score) +
        (0.20 * pacingPillar.score);

    final int overallScore = weightedScore.round().clamp(0, 100);

    HealthTier tier;
    if (overallScore >= 85) {
      tier = HealthTier.excellent;
    } else if (overallScore >= 70) {
      tier = HealthTier.good;
    } else if (overallScore >= 50) {
      tier = HealthTier.caution;
    } else {
      tier = HealthTier.deficit;
    }

    // =========================================================================
    // ACTIONABLE RECOMMENDATIONS
    // =========================================================================
    final List<String> recs = [];

    if (runwayMonths < 3.0) {
      recs.add(
        'Dana daruratmu (${runwayMonths.toStringAsFixed(1)} bulan) masih di bawah rekomendasi 3 bulan. Prioritaskan isi Kantong Darurat secara berkala.',
      );
    }
    if (commitmentRatio > 35.0) {
      recs.add(
        'Beban tagihan rutin mencapai ${commitmentRatio.toStringAsFixed(0)}% dari pemasukan. Evaluasi langganan atau tagihan yang kurang bernilai guna.',
      );
    }
    if (savingsMarginPercent < 10.0) {
      recs.add(
        'Margin tabungan bulan ini ${savingsMarginPercent.toStringAsFixed(0)}%. Terapkan sistem "Pay Yourself First" di awal tanggal gajian ke Kantong Impian.',
      );
    }
    if (safeToSpend.healthStatus != FinancialHealthStatus.comfortable) {
      recs.add(
        'Pacing belanja harian mendekati batas aman. Rem pengeluaran variabel agar tidak defisit di akhir bulan.',
      );
    }
    if (pockets.isEmpty) {
      recs.add(
        'Kamu belum memiliki Kantong Tabungan. Buat kantong alokasi (Masa Tua / Dana Darurat) untuk memisahkan dana jajan dari simpanan.',
      );
    }
    if (recs.isEmpty) {
      recs.add(
        'Kondisi keuanganmu luar biasa prima! Pertahankan rasio simpanan dan lanjutkan alokasi jangka panjang.',
      );
    }

    return FinancialHealthReport(
      overallScore: overallScore,
      tier: tier,
      emergencyRunway: emergencyPillar,
      fixedCommitment: commitmentPillar,
      savingsMargin: savingsPillar,
      spendPacing: pacingPillar,
      recommendations: recs,
      totalLiquidAssets: totalLiquidAssets,
      totalPocketsAmount: totalPocketsAmount,
    );
  }
}
